### ISSUE TITLE
Unicode text in PDF

### ISSUE THREAD

**Issue by emdadgar2** [DataTables/TableTools#10]
Generated PDF for unicode texts, will be fail.
If you use this table:
## a                   b

test           سلام

The output PDF will be:
## a                   b

test           ????

**Comment by justein** [comment]
I have encountered the same problem.. and still have no ideas。。。

**Comment by DataTables** [comment]
As noted in the posts I linked to, this is a limitation in the AlivePDF library.

The good news is that I've been working on a replacement to TableTools which uses a different library to create the PDFs. It will only support IE10+ (and all the other browsers of course), but it will support unicode.

Will be released by the middle of the month.

**Comment by emdadgar2** [comment]
Any new news?

**Comment by DataTables** [comment]
[Buttons](//datatables.net/extensions/buttons) replaced TableTools in 2015. TableTools is no longer in development/ Buttons does support UTF8 characters in the PDF HTML5 export.
