### ISSUE TITLE
datatable not working when data fetch by ajax

### ISSUE THREAD

**Issue by ghost** [DataTables/TableTools#112]
TableTools has now been retired and replaced by the Buttons and Select extensions for DataTables: https://datatables.net/extensions . TableTools is no longer being developed in favour of its replacements.

**i fetch all the data by using ajax bt problem is that datatable is not working like search paginatin sorting etc.**

<html>
   <table id="example" class="table table-hover">
                                      <thead>
                                      <th>S. No.</th>
                                      <th>Policy Name</th>
                                      <th>Left Hand Conditions</th>
                                      <th>Main Operator</th>
                                      <th>Right Hand Conditions</th>
                                      <th>Result</th>
                                      <th>Actions</th>
                                      <th>Delete</th>
                                      </thead>
                                          <tbody>

                                          </tbody>
                                      </table>
</html

function load_data()
        {
            $.ajax({
                url:"addNewPolicy.php",
                method:"POST",
                data:{auth_type:'fetch_all_policy'},
                dataType:'json',
                success:function(data)
                   {
                     var parse_data = '';
                     var sr = 1;
                     var html = '';
                    if(data != '')
                    {
                     for(var count = 0; count < data.value.length; count++)
                     {
                        parse_data = JSON.parse(data.value[count]);
                        //console.log(parse_data);
                        //return false;

                        html += '<tr class="main_tr" id="'+parse_data.policy_id+'">';
                        html += '<td colspan="8">';
                        html += '<table style="width:100%;">';
                        //------------------- add above query builder------------------------
                        html += '<tr class="add_above_row show_hide_policy_row" style="display:none;"><td colspan="8"><div class="row">';  
                        html += '<div class="col-md-3">';
                        html += '<div class="form-group mb-0">';
                        html += '<label>Policy Name</label>';   
                        html += '<input type="text" class="form-control policy_name" id="policy_name'+parse_data.policy_id+'above" name="policy_name" placeholder="policy name" required="required">';
                        html += '<p class="text-danger policy_name_error"></p>';
                        html += '</div>';                                            
                        html += '</div>';
                        html += '<div class="col-md-6">';
                        html += '<label>Policy Rule</label>'; 
                        html += '<div id="builder'+parse_data.policy_id+'above"></div>';
                        html += '</div>';
                        html += '<div class="col-md-3">';
                        html += '<div class="form-group mb-0">';
                        html += '<label>Policy Result </label>';
                        html += '<select class="form-control" id="policy_result'+parse_data.policy_id+'above" name="policy_result">';
                                for(var pol_res = 0; pol_res < policy_results.length; pol_res++)
                                {
                                    html += '<option value="'+policy_results[pol_res]+'">'+policy_results[pol_res]+'</option>';
                                }
                        html += '</select>';
                        html += '</div>';                                                                                    
                        html += '</div>';
                        html += '</div>';
                        html += '<div class="row">';
                        html += '<div class="col-md-12">';
                        html += '<button class="btn btn-primary btn-sm" onclick="addPolicy(this)" id="builder'+parse_data.policy_id+'above~policy_name'+parse_data.policy_id+'above~policy_result'+parse_data.policy_id+'above~'+data.policy_position[count]+'~ABOVE">Add Policy</button>';
                        html += '<button class="btn btn-danger btn-sm" onclick="hideCurrentSection()">Cancel</button>';
                        html += '</div>';
                        html += '</div></td></tr>';
                        html += '<td>'+sr+'</td>';
                        html += '<td>'+parse_data.policy_name+'</td>';                        
                        html += '</div>';                                                                                    
                        html += '</div>';
                        html += '</div>';
                        html += '<div class="row">';
                        html += '<div class="col-md-12">';
                        html += '<button class="btn btn-primary btn-sm"  onclick="editPolicy(this)" id="builder'+parse_data.policy_id+'edit~policy_name'+parse_data.policy_id+'~policy_result'+parse_data.policy_id+'~'+parse_data.policy_id+'">Add Policy</button>';
                        html += '<button class="btn btn-danger btn-sm" onclick="hideCurrentSection()">Cancel</button>';
                        html += '</div>';
                        html += '</div></td></tr>';

                        html += '</table>';
                        html += '</td>';
                        html += '</tr>';
                      sr++;
                     }
                    }
                    $('tbody').html(html);

        $('#mytable').DataTable();

**Comment by DataTables** [comment]
Hi - TableTools is legacy software and no longer supported.

For support questions on our current software, please ask them [in the DataTables forums](//datatables.net/forums).
