### ISSUE TITLE
File extension for TableTools.BUTTONS.xls is csv instead of xls

### ISSUE THREAD

**Issue by wachunga** [DataTables/TableTools#3]
I think this is a regression from TT 1. Shouldn't this be .xls?
https://github.com/DataTables/TableTools/blob/RELEASE_2_0_1/media/js/TableTools.js#L2063

**Comment by hanoncs** [comment]
Hello, Has this been rewritten? How can I fix? I still see this issue 4 years later.

**Comment by DataTables** [comment]
No not yet. It is in progress though.

**Comment by Ash5wini** [comment]
I am facing the same issue. Is the issue fixed. This is the only issue which is stopping me from using DataTable plugin as exporting data is one of the main functionalities in my application.

**Comment by DataTables** [comment]
TableTools has been replaced by the [Buttons extension](//datatables.net/extensions/buttons) now. I would suggest using that, it does create an XLSX file. Development on TableTools has been halted and will not be progressed further.
