### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Api' of undefined TableTools.js:2539

### ISSUE THREAD

**Issue by aranw** [DataTables/TableTools#39]
Trying to use DataTables and TableTools with Bower and RequireJS and I seem to get this error for some reason.  

`$.fn.dataTable` Exists but `$.fn.dataTable.Api` does not. 

Using DataTables Version 1.9.4 and TableTools Version 2.1.6-dev

**Comment by danpadua** [comment]
Remove possibles duplicates references of the datatables.responsive.js. Work for me perfectly.
