### ISSUE TITLE
TableTools not working in nested tab

### ISSUE THREAD

**Issue by kiempoturner** [DataTables/TableTools#79]
Im working on using TableTools in a nested tab. I've put the tables in separated file. The PDF and other exporting buttons only worked on the first tab. Nothing happens in other tabs except for the Print button. Here's the js file:
https://jsfiddle.net/kiempoturner/d0ynemzh/

The Code:

            
                    <div class="tab-content">

                        <div class="tab-pane active" id="tab_0">
                         <?php include 'table_report.php'; ?>
                        </div>

                        <div class="tab-pane" id="tab_1">
                         <?php include 'table_report_2.php'; ?>
                        </div>

                        <div class="tab-pane" id="tab_2">
                         <?php include 'table_report_3.php'; ?>
                        </div>

                        <div class="tab-pane" id="tab_3">
                         <?php include 'table_report_4.php'; ?>
                        </div>

                        <div class="tab-pane" id="tab_4">
                         <?php include 'table_report_5.php'; ?>
                        </div>

                        <div class="tab-pane" id="tab_5">
                         <?php include 'table_report_6.php'; ?>
                        </div>

                    </div>
            

Asked in SO too :
http://stackoverflow.com/questions/28873419/tabletools-not-working-in-nested-tab

**Comment by DataTables** [comment]
There are a number of discussions about this in the forum - [for example](https://www.datatables.net/forums/discussion/10988).

Basically you need to use the [`fnResizeButtons` API method](http://datatables.net/extensions/tabletools/api) when the tab is made visible so the Flash movie can be set to the correct size.
