### ISSUE TITLE
This does not work in IE

### ISSUE THREAD

**Issue by hyonaldo** [DataTables/TableTools#81]
I applied datatables-tabletools to our project.

<code>
./bower install --save datatables datatables-tabletools
</code>

and then I added this code to the controller (We use angularJS)

<code>
      $('#p'+$scope.paragraph.id+'_table .table').dataTable( {
        dom: 'T<"clear">lfrtip',
        tableTools: {
            "sSwfPath": "images/copy_csv_xls.swf"
        }
      });
<code>

This does work in Chrome, but doesn't work in IE

I can share the url below.
http://54.65.104.142:8080/#/notebook/2AFMGQDR8

Could anyone help me?

Since we use angular, I tried to use angular-datatables(http://l-lin.github.io/angular-datatables/). But it did not work in not only IE but also Chrome. ㅠ,.ㅠ

you can guess all versions of the libraries from below
    "angular": "1.3.8",
    "json3": "~3.3.1",
    "es5-shim": "~3.1.0",
    "bootstrap": "~3.2.0",
    "angular-cookies": "1.3.8",
    "angular-sanitize": "1.3.8",
    "angular-animate": "1.3.8",
    "angular-touch": "1.3.8",
    "angular-route": "1.3.8",
    "angular-bootstrap": "~0.11.0",
    "angular-websocket": "~0.0.5",
    "ace-builds": "1.1.8",
    "angular-ui-ace": "0.1.1",
    "jquery.scrollTo": "~1.4.13",
    "nvd3": "~1.1.15-beta",
    "angular-dragdrop": "~1.0.8",
    "perfect-scrollbar": "~0.5.4",
    "ng-sortable": "~1.1.9",
    "angular-elastic": "~2.4.2",
    "angular-elastic-input": "~2.0.1",
    "angular-xeditable": "0.1.8",
    "datatables": "~1.10.5",
    "datatables-tabletools": "~2.2.3"
    "ace-builds": {
      "main": [
        "src-noconflict/ace.js",
        "src-noconflict/mode-scala.js",
        "src-noconflict/mode-sql.js",
        "src-noconflict/mode-markdown.js",
        "src-noconflict/keybinding-emacs.js",
        "src-noconflict/ext-language_tools.js"
      ],
      "version": "1.1.8",
.....

Thank you. :)

**Comment by DataTables** [comment]
In future, can you post support requests in the [DataTables forums](//datatables.net/forums).

Do you have Flash installed in IE8?

**Comment by hyonaldo** [comment]
@DataTables 
Yes, I have installed flash in IE8.
But it doesn't work, too when I use DataTable() only. (except TableTools)
That's why I agree to your proposal  to post in the DataTables forums.
It's worth it.

**Comment by DataTables** [comment]
Can you link to your forum post please. Can you also state in your forum post if it works for you in the examples on the DataTables web-site or not.
