### ISSUE TITLE
Add new own tab function to the TableTools

### ISSUE THREAD

**Issue by Alkasih** [DataTables/TableTools#89]
I find that the tab-button is generated by action-script code. That's not a problem. But can I create new tab-button for my own functionality? How to link the action then? Thanks in advance

**Comment by MrGeneric** [comment]
Hi Alkasih,
The [DataTables forums](https://datatables.net/forums) is the place for questions like this, you're more likely to get help there. This Github is used for tracking bugs.

**Comment by DataTables** [comment]
Yes, you can use the `fnClick` option of the buttons to perform whatever custom action you want. This is in the documentation here: http://datatables.net/extensions/tabletools/button_options#fnClick .
