### ISSUE TITLE
Not exporting all the columns

### ISSUE THREAD

**Issue by komuravelly** [DataTables/TableTools#92]
Hi,

I am using table tools plugin v2.2.4.
When I click on export to pdf, I can see the basic table skeleton with data filled on first  column only.

Please do needful.

Thank you,
Uday
![capture](https://cloud.githubusercontent.com/assets/7005464/7574729/5bb88bb6-f7e4-11e4-948f-aec7d41cee96.JPG)

**Comment by DataTables** [comment]
Please link to a test case showing the issue.

**Comment by komuravelly** [comment]
I am not sure how to do that as this is happening in my application.

**Comment by komuravelly** [comment]
I am able to solve the problem.
I have another issue. Can I export only a few columns?

**Comment by DataTables** [comment]
Use the `mColumns` option: http://datatables.net/extensions/tabletools/button_options#mColumns

In future, can you please post support requests in the [DataTables forums](//datatables.net/forums).
