### ISSUE TITLE
Display table name in the exported pdf

### ISSUE THREAD

**Issue by komuravelly** [DataTables/TableTools#94]
Hi,

Could you please let me know how to display the table name in the exported PDF.
I have around 8 tables in the page, with export to PDF option. 

Thank you,
Uday

**Comment by DataTables** [comment]
You could use the [`sPdfMessage` option](http://datatables.net/extensions/tabletools/button_options#sPdfMessage).

In future, could you ask support questions in the [DataTables forums](//datatables.net/forums) please.
