### ISSUE TITLE
Excel export: Filters not applied

### ISSUE THREAD

**Issue by sgotre** [DataTables/TableTools#96]
When exporting a table to Excel (csv) the current text filter is not applied. 
The downloaded file always includes the full table. 
Neither the column filter is applied nor the "full table search filter"

In an older Version (v2.1.4 / TableTools.min.js) in combination with jquery.dataTables.columnFilter.js (v 1.5.0) by Jovan Popovic the filter was applied to the excel list.

Is this a bug or a feature? How can I apply the filter to the excel file too?  

This occurs with the latest version of TableTools and with client side filtering. 
To reproduce you can use this page https://datatables.net/extensions/tabletools/ enter something into "search" and download the Excel file - it will contain the whole table.

**Comment by DataTables** [comment]
Use the [`oSelectorOpts` option](https://datatables.net/extensions/tabletools/button_options#oSelectorOpts) to tell TableTools what to export.

Can you post future support requests in the [DataTables forums](//datatables.net/forums) please?
